#
# Module manifest for module 'Microsoft.Graph.Teams'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/16/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Teams.psm1'

# Version number of this module.
ModuleVersion = '2.29.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f8619bb2-8640-4d8d-baf5-0829db98fbe2'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.29.1'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Teams.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Teams.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgChatMember', 'Add-MgGroupTeamChannelAllMember', 
               'Add-MgGroupTeamChannelMember', 'Add-MgGroupTeamMember', 
               'Add-MgGroupTeamPrimaryChannelAllMember', 
               'Add-MgGroupTeamPrimaryChannelMember', 'Add-MgTeamChannelAllMember', 
               'Add-MgTeamChannelMember', 'Add-MgTeamMember', 
               'Add-MgTeamPrimaryChannelAllMember', 
               'Add-MgTeamPrimaryChannelMember', 
               'Add-MgTeamworkDeletedTeamChannelAllMember', 
               'Add-MgTeamworkDeletedTeamChannelMember', 'Add-MgUserChatMember', 
               'Clear-MgChatMessageReaction', 'Clear-MgChatMessageReplyReaction', 
               'Clear-MgGroupTeamChannelMessageReaction', 
               'Clear-MgGroupTeamChannelMessageReplyReaction', 
               'Clear-MgGroupTeamPrimaryChannelMessageReaction', 
               'Clear-MgGroupTeamPrimaryChannelMessageReplyReaction', 
               'Clear-MgTeamChannelMessageReaction', 
               'Clear-MgTeamChannelMessageReplyReaction', 
               'Clear-MgTeamPrimaryChannelMessageReaction', 
               'Clear-MgTeamPrimaryChannelMessageReplyReaction', 
               'Clear-MgTeamworkDeletedTeamChannelMessageReaction', 
               'Clear-MgTeamworkDeletedTeamChannelMessageReplyReaction', 
               'Clear-MgUserChatMessageReaction', 
               'Clear-MgUserChatMessageReplyReaction', 
               'Complete-MgGroupTeamChannelMigration', 
               'Complete-MgGroupTeamMigration', 
               'Complete-MgGroupTeamPrimaryChannelMigration', 
               'Complete-MgTeamChannelMigration', 'Complete-MgTeamMigration', 
               'Complete-MgTeamPrimaryChannelMigration', 
               'Complete-MgTeamworkDeletedTeamChannelMigration', 
               'Confirm-MgGroupTeamScheduleTimeCard', 
               'Confirm-MgTeamScheduleTimeCard', 'Copy-MgGroupTeam', 'Copy-MgTeam', 
               'Get-MgAllGroupTeamChannel', 'Get-MgAllGroupTeamChannelCount', 
               'Get-MgAllTeamChannel', 'Get-MgAllTeamChannelCount', 
               'Get-MgAllTeamMessage', 'Get-MgAllTeamworkDeletedTeamMessage', 
               'Get-MgAllUserChatMessage', 'Get-MgAppCatalogTeamApp', 
               'Get-MgAppCatalogTeamAppCount', 'Get-MgAppCatalogTeamAppDefinition', 
               'Get-MgAppCatalogTeamAppDefinitionBot', 
               'Get-MgAppCatalogTeamAppDefinitionCount', 'Get-MgChat', 
               'Get-MgChatCount', 'Get-MgChatInstalledApp', 
               'Get-MgChatInstalledAppCount', 'Get-MgChatInstalledAppTeamApp', 
               'Get-MgChatInstalledAppTeamAppDefinition', 
               'Get-MgChatLastMessagePreview', 'Get-MgChatMember', 
               'Get-MgChatMemberCount', 'Get-MgChatMessage', 
               'Get-MgChatMessageCount', 'Get-MgChatMessageDelta', 
               'Get-MgChatMessageHostedContent', 
               'Get-MgChatMessageHostedContentCount', 'Get-MgChatMessageReply', 
               'Get-MgChatMessageReplyCount', 'Get-MgChatMessageReplyDelta', 
               'Get-MgChatMessageReplyHostedContent', 
               'Get-MgChatMessageReplyHostedContentCount', 
               'Get-MgChatPermissionGrant', 'Get-MgChatPermissionGrantCount', 
               'Get-MgChatPinnedMessage', 'Get-MgChatPinnedMessageCount', 
               'Get-MgChatRetainedMessage', 'Get-MgChatTab', 'Get-MgChatTabCount', 
               'Get-MgChatTabTeamApp', 'Get-MgGroupTeam', 'Get-MgGroupTeamChannel', 
               'Get-MgGroupTeamChannelAllMemberCount', 
               'Get-MgGroupTeamChannelCount', 'Get-MgGroupTeamChannelFileFolder', 
               'Get-MgGroupTeamChannelFileFolderContent', 
               'Get-MgGroupTeamChannelMember', 'Get-MgGroupTeamChannelMemberCount', 
               'Get-MgGroupTeamChannelMessage', 
               'Get-MgGroupTeamChannelMessageCount', 
               'Get-MgGroupTeamChannelMessageDelta', 
               'Get-MgGroupTeamChannelMessageHostedContent', 
               'Get-MgGroupTeamChannelMessageHostedContentCount', 
               'Get-MgGroupTeamChannelMessageReply', 
               'Get-MgGroupTeamChannelMessageReplyCount', 
               'Get-MgGroupTeamChannelMessageReplyDelta', 
               'Get-MgGroupTeamChannelMessageReplyHostedContent', 
               'Get-MgGroupTeamChannelMessageReplyHostedContentCount', 
               'Get-MgGroupTeamChannelRetainedMessage', 
               'Get-MgGroupTeamChannelSharedWithTeam', 
               'Get-MgGroupTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgGroupTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgGroupTeamChannelSharedWithTeamCount', 
               'Get-MgGroupTeamChannelTab', 'Get-MgGroupTeamChannelTabCount', 
               'Get-MgGroupTeamChannelTabTeamApp', 'Get-MgGroupTeamGroup', 
               'Get-MgGroupTeamGroupServiceProvisioningError', 
               'Get-MgGroupTeamGroupServiceProvisioningErrorCount', 
               'Get-MgGroupTeamIncomingChannel', 
               'Get-MgGroupTeamIncomingChannelCount', 
               'Get-MgGroupTeamInstalledApp', 'Get-MgGroupTeamInstalledAppCount', 
               'Get-MgGroupTeamInstalledAppTeamApp', 
               'Get-MgGroupTeamInstalledAppTeamAppDefinition', 
               'Get-MgGroupTeamMember', 'Get-MgGroupTeamMemberCount', 
               'Get-MgGroupTeamOperation', 'Get-MgGroupTeamOperationCount', 
               'Get-MgGroupTeamPermissionGrant', 
               'Get-MgGroupTeamPermissionGrantCount', 'Get-MgGroupTeamPhoto', 
               'Get-MgGroupTeamPhotoContent', 'Get-MgGroupTeamPrimaryChannel', 
               'Get-MgGroupTeamPrimaryChannelAllMemberCount', 
               'Get-MgGroupTeamPrimaryChannelFileFolder', 
               'Get-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Get-MgGroupTeamPrimaryChannelMember', 
               'Get-MgGroupTeamPrimaryChannelMemberCount', 
               'Get-MgGroupTeamPrimaryChannelMessage', 
               'Get-MgGroupTeamPrimaryChannelMessageCount', 
               'Get-MgGroupTeamPrimaryChannelMessageDelta', 
               'Get-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Get-MgGroupTeamPrimaryChannelMessageHostedContentCount', 
               'Get-MgGroupTeamPrimaryChannelMessageReply', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyCount', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyDelta', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Get-MgGroupTeamPrimaryChannelMessageReplyHostedContentCount', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamAllowedMember', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgGroupTeamPrimaryChannelSharedWithTeamCount', 
               'Get-MgGroupTeamPrimaryChannelTab', 
               'Get-MgGroupTeamPrimaryChannelTabCount', 
               'Get-MgGroupTeamPrimaryChannelTabTeamApp', 
               'Get-MgGroupTeamSchedule', 'Get-MgGroupTeamScheduleDayNote', 
               'Get-MgGroupTeamScheduleDayNoteCount', 
               'Get-MgGroupTeamScheduleOfferShiftRequest', 
               'Get-MgGroupTeamScheduleOfferShiftRequestCount', 
               'Get-MgGroupTeamScheduleOpenShift', 
               'Get-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Get-MgGroupTeamScheduleOpenShiftChangeRequestCount', 
               'Get-MgGroupTeamScheduleOpenShiftCount', 
               'Get-MgGroupTeamScheduleSchedulingGroup', 
               'Get-MgGroupTeamScheduleSchedulingGroupCount', 
               'Get-MgGroupTeamScheduleShift', 'Get-MgGroupTeamScheduleShiftCount', 
               'Get-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Get-MgGroupTeamScheduleSwapShiftChangeRequestCount', 
               'Get-MgGroupTeamScheduleTimeCard', 
               'Get-MgGroupTeamScheduleTimeCardCount', 
               'Get-MgGroupTeamScheduleTimeOff', 
               'Get-MgGroupTeamScheduleTimeOffCount', 
               'Get-MgGroupTeamScheduleTimeOffReason', 
               'Get-MgGroupTeamScheduleTimeOffReasonCount', 
               'Get-MgGroupTeamScheduleTimeOffRequest', 
               'Get-MgGroupTeamScheduleTimeOffRequestCount', 'Get-MgGroupTeamTag', 
               'Get-MgGroupTeamTagCount', 'Get-MgGroupTeamTagMember', 
               'Get-MgGroupTeamTagMemberCount', 'Get-MgGroupTeamTemplate', 
               'Get-MgTeam', 'Get-MgTeamChannel', 'Get-MgTeamChannelAllMemberCount', 
               'Get-MgTeamChannelCount', 'Get-MgTeamChannelFileFolder', 
               'Get-MgTeamChannelFileFolderContent', 'Get-MgTeamChannelMember', 
               'Get-MgTeamChannelMemberCount', 'Get-MgTeamChannelMessage', 
               'Get-MgTeamChannelMessageCount', 'Get-MgTeamChannelMessageDelta', 
               'Get-MgTeamChannelMessageHostedContent', 
               'Get-MgTeamChannelMessageHostedContentCount', 
               'Get-MgTeamChannelMessageReply', 
               'Get-MgTeamChannelMessageReplyCount', 
               'Get-MgTeamChannelMessageReplyDelta', 
               'Get-MgTeamChannelMessageReplyHostedContent', 
               'Get-MgTeamChannelMessageReplyHostedContentCount', 
               'Get-MgTeamChannelRetainedMessage', 
               'Get-MgTeamChannelSharedWithTeam', 
               'Get-MgTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamChannelSharedWithTeamCount', 'Get-MgTeamChannelTab', 
               'Get-MgTeamChannelTabCount', 'Get-MgTeamChannelTabTeamApp', 
               'Get-MgTeamCount', 'Get-MgTeamGroupServiceProvisioningError', 
               'Get-MgTeamGroupServiceProvisioningErrorCount', 
               'Get-MgTeamIncomingChannel', 'Get-MgTeamIncomingChannelCount', 
               'Get-MgTeamInstalledApp', 'Get-MgTeamInstalledAppCount', 
               'Get-MgTeamInstalledAppTeamApp', 
               'Get-MgTeamInstalledAppTeamAppDefinition', 'Get-MgTeamMember', 
               'Get-MgTeamMemberCount', 'Get-MgTeamOperation', 
               'Get-MgTeamOperationCount', 'Get-MgTeamPermissionGrant', 
               'Get-MgTeamPermissionGrantCount', 'Get-MgTeamPhoto', 
               'Get-MgTeamPhotoContent', 'Get-MgTeamPrimaryChannel', 
               'Get-MgTeamPrimaryChannelAllMemberCount', 
               'Get-MgTeamPrimaryChannelFileFolder', 
               'Get-MgTeamPrimaryChannelFileFolderContent', 
               'Get-MgTeamPrimaryChannelMember', 
               'Get-MgTeamPrimaryChannelMemberCount', 
               'Get-MgTeamPrimaryChannelMessage', 
               'Get-MgTeamPrimaryChannelMessageCount', 
               'Get-MgTeamPrimaryChannelMessageDelta', 
               'Get-MgTeamPrimaryChannelMessageHostedContent', 
               'Get-MgTeamPrimaryChannelMessageHostedContentCount', 
               'Get-MgTeamPrimaryChannelMessageReply', 
               'Get-MgTeamPrimaryChannelMessageReplyCount', 
               'Get-MgTeamPrimaryChannelMessageReplyDelta', 
               'Get-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Get-MgTeamPrimaryChannelMessageReplyHostedContentCount', 
               'Get-MgTeamPrimaryChannelSharedWithTeam', 
               'Get-MgTeamPrimaryChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamPrimaryChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamPrimaryChannelSharedWithTeamCount', 
               'Get-MgTeamPrimaryChannelTab', 'Get-MgTeamPrimaryChannelTabCount', 
               'Get-MgTeamPrimaryChannelTabTeamApp', 'Get-MgTeamSchedule', 
               'Get-MgTeamScheduleDayNote', 'Get-MgTeamScheduleDayNoteCount', 
               'Get-MgTeamScheduleOfferShiftRequest', 
               'Get-MgTeamScheduleOfferShiftRequestCount', 
               'Get-MgTeamScheduleOpenShift', 
               'Get-MgTeamScheduleOpenShiftChangeRequest', 
               'Get-MgTeamScheduleOpenShiftChangeRequestCount', 
               'Get-MgTeamScheduleOpenShiftCount', 
               'Get-MgTeamScheduleSchedulingGroup', 
               'Get-MgTeamScheduleSchedulingGroupCount', 'Get-MgTeamScheduleShift', 
               'Get-MgTeamScheduleShiftCount', 
               'Get-MgTeamScheduleSwapShiftChangeRequest', 
               'Get-MgTeamScheduleSwapShiftChangeRequestCount', 
               'Get-MgTeamScheduleTimeCard', 'Get-MgTeamScheduleTimeCardCount', 
               'Get-MgTeamScheduleTimeOff', 'Get-MgTeamScheduleTimeOffCount', 
               'Get-MgTeamScheduleTimeOffReason', 
               'Get-MgTeamScheduleTimeOffReasonCount', 
               'Get-MgTeamScheduleTimeOffRequest', 
               'Get-MgTeamScheduleTimeOffRequestCount', 'Get-MgTeamTag', 
               'Get-MgTeamTagCount', 'Get-MgTeamTagMember', 
               'Get-MgTeamTagMemberCount', 'Get-MgTeamTemplate', 'Get-MgTeamwork', 
               'Get-MgTeamworkDeletedChat', 'Get-MgTeamworkDeletedChatCount', 
               'Get-MgTeamworkDeletedTeam', 'Get-MgTeamworkDeletedTeamChannel', 
               'Get-MgTeamworkDeletedTeamChannelAllMemberCount', 
               'Get-MgTeamworkDeletedTeamChannelCount', 
               'Get-MgTeamworkDeletedTeamChannelFileFolder', 
               'Get-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Get-MgTeamworkDeletedTeamChannelMember', 
               'Get-MgTeamworkDeletedTeamChannelMemberCount', 
               'Get-MgTeamworkDeletedTeamChannelMessage', 
               'Get-MgTeamworkDeletedTeamChannelMessageCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageDelta', 
               'Get-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Get-MgTeamworkDeletedTeamChannelMessageHostedContentCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageReply', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyCount', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyDelta', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Get-MgTeamworkDeletedTeamChannelMessageReplyHostedContentCount', 
               'Get-MgTeamworkDeletedTeamChannelRetainedMessage', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamAllowedMember', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamAllowedMemberCount', 
               'Get-MgTeamworkDeletedTeamChannelSharedWithTeamCount', 
               'Get-MgTeamworkDeletedTeamChannelTab', 
               'Get-MgTeamworkDeletedTeamChannelTabCount', 
               'Get-MgTeamworkDeletedTeamChannelTabTeamApp', 
               'Get-MgTeamworkDeletedTeamCount', 'Get-MgTeamworkTeamAppSetting', 
               'Get-MgTeamworkWorkforceIntegration', 
               'Get-MgTeamworkWorkforceIntegrationCount', 'Get-MgUserChat', 
               'Get-MgUserChatCount', 'Get-MgUserChatInstalledApp', 
               'Get-MgUserChatInstalledAppCount', 
               'Get-MgUserChatInstalledAppTeamApp', 
               'Get-MgUserChatInstalledAppTeamAppDefinition', 
               'Get-MgUserChatLastMessagePreview', 'Get-MgUserChatMember', 
               'Get-MgUserChatMemberCount', 'Get-MgUserChatMessageCount', 
               'Get-MgUserChatMessageDelta', 'Get-MgUserChatMessageHostedContent', 
               'Get-MgUserChatMessageHostedContentCount', 
               'Get-MgUserChatMessageReply', 'Get-MgUserChatMessageReplyCount', 
               'Get-MgUserChatMessageReplyDelta', 
               'Get-MgUserChatMessageReplyHostedContent', 
               'Get-MgUserChatMessageReplyHostedContentCount', 
               'Get-MgUserChatPermissionGrant', 
               'Get-MgUserChatPermissionGrantCount', 'Get-MgUserChatPinnedMessage', 
               'Get-MgUserChatPinnedMessageCount', 'Get-MgUserChatRetainedMessage', 
               'Get-MgUserChatTab', 'Get-MgUserChatTabCount', 
               'Get-MgUserChatTabTeamApp', 'Get-MgUserJoinedTeam', 
               'Get-MgUserTeamwork', 'Get-MgUserTeamworkAssociatedTeam', 
               'Get-MgUserTeamworkAssociatedTeamCount', 
               'Get-MgUserTeamworkInstalledApp', 
               'Get-MgUserTeamworkInstalledAppChat', 
               'Get-MgUserTeamworkInstalledAppCount', 
               'Get-MgUserTeamworkInstalledAppTeamApp', 
               'Get-MgUserTeamworkInstalledAppTeamAppDefinition', 
               'Hide-MgChatForUser', 'Hide-MgUserChatForUser', 
               'Invoke-MgArchiveGroupTeam', 'Invoke-MgArchiveGroupTeamChannel', 
               'Invoke-MgArchiveGroupTeamPrimaryChannel', 'Invoke-MgArchiveTeam', 
               'Invoke-MgArchiveTeamChannel', 'Invoke-MgArchiveTeamPrimaryChannel', 
               'Invoke-MgArchiveTeamworkDeletedTeamChannel', 
               'Invoke-MgClockGroupTeamScheduleTimeCardIn', 
               'Invoke-MgClockGroupTeamScheduleTimeCardOut', 
               'Invoke-MgClockTeamScheduleTimeCardIn', 
               'Invoke-MgClockTeamScheduleTimeCardOut', 'Invoke-MgGraphChat', 
               'Invoke-MgGraphUserChat', 'Invoke-MgHaveGroupTeamChannel', 
               'Invoke-MgHaveGroupTeamPrimaryChannel', 'Invoke-MgHaveTeamChannel', 
               'Invoke-MgHaveTeamPrimaryChannel', 
               'Invoke-MgHaveTeamworkDeletedTeamChannel', 
               'Invoke-MgMarkChatReadForUser', 'Invoke-MgMarkChatUnreadForUser', 
               'Invoke-MgMarkUserChatReadForUser', 
               'Invoke-MgMarkUserChatUnreadForUser', 
               'Invoke-MgShareGroupTeamSchedule', 'Invoke-MgShareTeamSchedule', 
               'Invoke-MgSoftChatMessageDelete', 
               'Invoke-MgSoftChatMessageReplyDelete', 
               'Invoke-MgSoftGroupTeamChannelMessageDelete', 
               'Invoke-MgSoftGroupTeamChannelMessageReplyDelete', 
               'Invoke-MgSoftGroupTeamPrimaryChannelMessageDelete', 
               'Invoke-MgSoftGroupTeamPrimaryChannelMessageReplyDelete', 
               'Invoke-MgSoftTeamChannelMessageDelete', 
               'Invoke-MgSoftTeamChannelMessageReplyDelete', 
               'Invoke-MgSoftTeamPrimaryChannelMessageDelete', 
               'Invoke-MgSoftTeamPrimaryChannelMessageReplyDelete', 
               'Invoke-MgSoftTeamworkDeletedTeamChannelMessageDelete', 
               'Invoke-MgSoftTeamworkDeletedTeamChannelMessageReplyDelete', 
               'Invoke-MgSoftUserChatMessageDelete', 
               'Invoke-MgSoftUserChatMessageReplyDelete', 
               'Invoke-MgUnarchiveGroupTeam', 'Invoke-MgUnarchiveGroupTeamChannel', 
               'Invoke-MgUnarchiveGroupTeamPrimaryChannel', 
               'Invoke-MgUnarchiveTeam', 'Invoke-MgUnarchiveTeamChannel', 
               'Invoke-MgUnarchiveTeamPrimaryChannel', 
               'Invoke-MgUnarchiveTeamworkDeletedTeamChannel', 
               'New-MgAppCatalogTeamApp', 'New-MgAppCatalogTeamAppDefinition', 
               'New-MgChat', 'New-MgChatInstalledApp', 'New-MgChatMember', 
               'New-MgChatMessage', 'New-MgChatMessageHostedContent', 
               'New-MgChatMessageReply', 'New-MgChatMessageReplyHostedContent', 
               'New-MgChatPermissionGrant', 'New-MgChatPinnedMessage', 
               'New-MgChatTab', 'New-MgGroupTeamChannel', 
               'New-MgGroupTeamChannelEmail', 'New-MgGroupTeamChannelMember', 
               'New-MgGroupTeamChannelMessage', 
               'New-MgGroupTeamChannelMessageHostedContent', 
               'New-MgGroupTeamChannelMessageReply', 
               'New-MgGroupTeamChannelMessageReplyHostedContent', 
               'New-MgGroupTeamChannelSharedWithTeam', 'New-MgGroupTeamChannelTab', 
               'New-MgGroupTeamInstalledApp', 'New-MgGroupTeamMember', 
               'New-MgGroupTeamOperation', 'New-MgGroupTeamPermissionGrant', 
               'New-MgGroupTeamPrimaryChannelEmail', 
               'New-MgGroupTeamPrimaryChannelMember', 
               'New-MgGroupTeamPrimaryChannelMessage', 
               'New-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'New-MgGroupTeamPrimaryChannelMessageReply', 
               'New-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'New-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'New-MgGroupTeamPrimaryChannelTab', 
               'New-MgGroupTeamScheduleDayNote', 
               'New-MgGroupTeamScheduleOfferShiftRequest', 
               'New-MgGroupTeamScheduleOpenShift', 
               'New-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'New-MgGroupTeamScheduleSchedulingGroup', 
               'New-MgGroupTeamScheduleShift', 
               'New-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'New-MgGroupTeamScheduleTimeCard', 'New-MgGroupTeamScheduleTimeOff', 
               'New-MgGroupTeamScheduleTimeOffReason', 
               'New-MgGroupTeamScheduleTimeOffRequest', 'New-MgGroupTeamTag', 
               'New-MgGroupTeamTagMember', 'New-MgTeam', 'New-MgTeamChannel', 
               'New-MgTeamChannelEmail', 'New-MgTeamChannelMember', 
               'New-MgTeamChannelMessage', 'New-MgTeamChannelMessageHostedContent', 
               'New-MgTeamChannelMessageReply', 
               'New-MgTeamChannelMessageReplyHostedContent', 
               'New-MgTeamChannelSharedWithTeam', 'New-MgTeamChannelTab', 
               'New-MgTeamInstalledApp', 'New-MgTeamMember', 'New-MgTeamOperation', 
               'New-MgTeamPermissionGrant', 'New-MgTeamPrimaryChannelEmail', 
               'New-MgTeamPrimaryChannelMember', 'New-MgTeamPrimaryChannelMessage', 
               'New-MgTeamPrimaryChannelMessageHostedContent', 
               'New-MgTeamPrimaryChannelMessageReply', 
               'New-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'New-MgTeamPrimaryChannelSharedWithTeam', 
               'New-MgTeamPrimaryChannelTab', 'New-MgTeamScheduleDayNote', 
               'New-MgTeamScheduleOfferShiftRequest', 
               'New-MgTeamScheduleOpenShift', 
               'New-MgTeamScheduleOpenShiftChangeRequest', 
               'New-MgTeamScheduleSchedulingGroup', 'New-MgTeamScheduleShift', 
               'New-MgTeamScheduleSwapShiftChangeRequest', 
               'New-MgTeamScheduleTimeCard', 'New-MgTeamScheduleTimeOff', 
               'New-MgTeamScheduleTimeOffReason', 
               'New-MgTeamScheduleTimeOffRequest', 'New-MgTeamTag', 
               'New-MgTeamTagMember', 'New-MgTeamworkDeletedChat', 
               'New-MgTeamworkDeletedTeam', 'New-MgTeamworkDeletedTeamChannel', 
               'New-MgTeamworkDeletedTeamChannelEmail', 
               'New-MgTeamworkDeletedTeamChannelMember', 
               'New-MgTeamworkDeletedTeamChannelMessage', 
               'New-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'New-MgTeamworkDeletedTeamChannelMessageReply', 
               'New-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'New-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'New-MgTeamworkDeletedTeamChannelTab', 
               'New-MgTeamworkWorkforceIntegration', 'New-MgUserChat', 
               'New-MgUserChatInstalledApp', 'New-MgUserChatMember', 
               'New-MgUserChatMessage', 'New-MgUserChatMessageHostedContent', 
               'New-MgUserChatMessageReply', 
               'New-MgUserChatMessageReplyHostedContent', 
               'New-MgUserChatPermissionGrant', 'New-MgUserChatPinnedMessage', 
               'New-MgUserChatTab', 'New-MgUserTeamworkAssociatedTeam', 
               'New-MgUserTeamworkInstalledApp', 'Remove-MgAppCatalogTeamApp', 
               'Remove-MgAppCatalogTeamAppDefinition', 
               'Remove-MgAppCatalogTeamAppDefinitionBot', 'Remove-MgChat', 
               'Remove-MgChatInstalledApp', 'Remove-MgChatLastMessagePreview', 
               'Remove-MgChatMember', 'Remove-MgChatMessageReplyHostedContent', 
               'Remove-MgChatPermissionGrant', 'Remove-MgChatPinnedMessage', 
               'Remove-MgChatTab', 'Remove-MgGroupTeam', 'Remove-MgGroupTeamChannel', 
               'Remove-MgGroupTeamChannelAllMember', 
               'Remove-MgGroupTeamChannelEmail', 
               'Remove-MgGroupTeamChannelFileFolderContent', 
               'Remove-MgGroupTeamChannelMember', 
               'Remove-MgGroupTeamChannelMessage', 
               'Remove-MgGroupTeamChannelMessageHostedContent', 
               'Remove-MgGroupTeamChannelMessageReply', 
               'Remove-MgGroupTeamChannelMessageReplyHostedContent', 
               'Remove-MgGroupTeamChannelSharedWithTeam', 
               'Remove-MgGroupTeamChannelTab', 'Remove-MgGroupTeamInstalledApp', 
               'Remove-MgGroupTeamMember', 'Remove-MgGroupTeamOperation', 
               'Remove-MgGroupTeamPermissionGrant', 
               'Remove-MgGroupTeamPhotoContent', 
               'Remove-MgGroupTeamPrimaryChannel', 
               'Remove-MgGroupTeamPrimaryChannelAllMember', 
               'Remove-MgGroupTeamPrimaryChannelEmail', 
               'Remove-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Remove-MgGroupTeamPrimaryChannelMember', 
               'Remove-MgGroupTeamPrimaryChannelMessage', 
               'Remove-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Remove-MgGroupTeamPrimaryChannelMessageReply', 
               'Remove-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Remove-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Remove-MgGroupTeamPrimaryChannelTab', 'Remove-MgGroupTeamSchedule', 
               'Remove-MgGroupTeamScheduleDayNote', 
               'Remove-MgGroupTeamScheduleOfferShiftRequest', 
               'Remove-MgGroupTeamScheduleOpenShift', 
               'Remove-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Remove-MgGroupTeamScheduleSchedulingGroup', 
               'Remove-MgGroupTeamScheduleShift', 
               'Remove-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Remove-MgGroupTeamScheduleTimeCard', 
               'Remove-MgGroupTeamScheduleTimeOff', 
               'Remove-MgGroupTeamScheduleTimeOffReason', 
               'Remove-MgGroupTeamScheduleTimeOffRequest', 'Remove-MgGroupTeamTag', 
               'Remove-MgGroupTeamTagMember', 'Remove-MgTeam', 
               'Remove-MgTeamChannel', 'Remove-MgTeamChannelAllMember', 
               'Remove-MgTeamChannelEmail', 
               'Remove-MgTeamChannelFileFolderContent', 
               'Remove-MgTeamChannelMember', 
               'Remove-MgTeamChannelMessageReplyHostedContent', 
               'Remove-MgTeamChannelSharedWithTeam', 'Remove-MgTeamChannelTab', 
               'Remove-MgTeamInstalledApp', 'Remove-MgTeamMember', 
               'Remove-MgTeamOperation', 'Remove-MgTeamPermissionGrant', 
               'Remove-MgTeamPhotoContent', 'Remove-MgTeamPrimaryChannel', 
               'Remove-MgTeamPrimaryChannelAllMember', 
               'Remove-MgTeamPrimaryChannelEmail', 
               'Remove-MgTeamPrimaryChannelFileFolderContent', 
               'Remove-MgTeamPrimaryChannelMember', 
               'Remove-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Remove-MgTeamPrimaryChannelSharedWithTeam', 
               'Remove-MgTeamPrimaryChannelTab', 'Remove-MgTeamSchedule', 
               'Remove-MgTeamScheduleDayNote', 
               'Remove-MgTeamScheduleOfferShiftRequest', 
               'Remove-MgTeamScheduleOpenShift', 
               'Remove-MgTeamScheduleOpenShiftChangeRequest', 
               'Remove-MgTeamScheduleSchedulingGroup', 
               'Remove-MgTeamScheduleShift', 
               'Remove-MgTeamScheduleSwapShiftChangeRequest', 
               'Remove-MgTeamScheduleTimeCard', 'Remove-MgTeamScheduleTimeOff', 
               'Remove-MgTeamScheduleTimeOffReason', 
               'Remove-MgTeamScheduleTimeOffRequest', 'Remove-MgTeamTag', 
               'Remove-MgTeamTagMember', 'Remove-MgTeamworkDeletedChat', 
               'Remove-MgTeamworkDeletedTeam', 
               'Remove-MgTeamworkDeletedTeamChannel', 
               'Remove-MgTeamworkDeletedTeamChannelAllMember', 
               'Remove-MgTeamworkDeletedTeamChannelEmail', 
               'Remove-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Remove-MgTeamworkDeletedTeamChannelMember', 
               'Remove-MgTeamworkDeletedTeamChannelMessage', 
               'Remove-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Remove-MgTeamworkDeletedTeamChannelMessageReply', 
               'Remove-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Remove-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Remove-MgTeamworkDeletedTeamChannelTab', 
               'Remove-MgTeamworkTeamAppSetting', 
               'Remove-MgTeamworkWorkforceIntegration', 'Remove-MgUserChat', 
               'Remove-MgUserChatInstalledApp', 
               'Remove-MgUserChatLastMessagePreview', 'Remove-MgUserChatMember', 
               'Remove-MgUserChatMessage', 'Remove-MgUserChatMessageHostedContent', 
               'Remove-MgUserChatMessageReply', 
               'Remove-MgUserChatMessageReplyHostedContent', 
               'Remove-MgUserChatPermissionGrant', 
               'Remove-MgUserChatPinnedMessage', 'Remove-MgUserChatTab', 
               'Remove-MgUserTeamwork', 'Remove-MgUserTeamworkAssociatedTeam', 
               'Remove-MgUserTeamworkInstalledApp', 
               'Send-MgChatActivityNotification', 
               'Send-MgGroupTeamActivityNotification', 
               'Send-MgTeamActivityNotification', 
               'Send-MgTeamworkActivityNotificationToRecipient', 
               'Send-MgUserChatActivityNotification', 
               'Send-MgUserTeamworkActivityNotification', 
               'Set-MgChatMessageHostedContent', 'Set-MgChatMessageReaction', 
               'Set-MgChatMessageReplyHostedContent', 
               'Set-MgChatMessageReplyReaction', 'Set-MgGroupTeam', 
               'Set-MgGroupTeamChannelFileFolderContent', 
               'Set-MgGroupTeamChannelMessageHostedContent', 
               'Set-MgGroupTeamChannelMessageReaction', 
               'Set-MgGroupTeamChannelMessageReplyHostedContent', 
               'Set-MgGroupTeamChannelMessageReplyReaction', 
               'Set-MgGroupTeamPhotoContent', 
               'Set-MgGroupTeamPrimaryChannelFileFolderContent', 
               'Set-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Set-MgGroupTeamPrimaryChannelMessageReaction', 
               'Set-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Set-MgGroupTeamPrimaryChannelMessageReplyReaction', 
               'Set-MgGroupTeamSchedule', 'Set-MgTeamChannelFileFolderContent', 
               'Set-MgTeamChannelMessageHostedContent', 
               'Set-MgTeamChannelMessageReaction', 
               'Set-MgTeamChannelMessageReplyHostedContent', 
               'Set-MgTeamChannelMessageReplyReaction', 'Set-MgTeamPhotoContent', 
               'Set-MgTeamPrimaryChannelFileFolderContent', 
               'Set-MgTeamPrimaryChannelMessageHostedContent', 
               'Set-MgTeamPrimaryChannelMessageReaction', 
               'Set-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Set-MgTeamPrimaryChannelMessageReplyReaction', 
               'Set-MgTeamSchedule', 
               'Set-MgTeamworkDeletedTeamChannelFileFolderContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageReaction', 
               'Set-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Set-MgTeamworkDeletedTeamChannelMessageReplyReaction', 
               'Set-MgUserChatMessageHostedContent', 
               'Set-MgUserChatMessageReaction', 
               'Set-MgUserChatMessageReplyHostedContent', 
               'Set-MgUserChatMessageReplyReaction', 
               'Start-MgGroupTeamScheduleTimeCardBreak', 
               'Start-MgTeamScheduleTimeCardBreak', 
               'Stop-MgGroupTeamScheduleTimeCardBreak', 
               'Stop-MgTeamScheduleTimeCardBreak', 
               'Undo-MgChatMessageReplySoftDelete', 'Undo-MgChatMessageSoftDelete', 
               'Undo-MgGroupTeamChannelMessageReplySoftDelete', 
               'Undo-MgGroupTeamChannelMessageSoftDelete', 
               'Undo-MgGroupTeamPrimaryChannelMessageReplySoftDelete', 
               'Undo-MgGroupTeamPrimaryChannelMessageSoftDelete', 
               'Undo-MgTeamChannelMessageReplySoftDelete', 
               'Undo-MgTeamChannelMessageSoftDelete', 
               'Undo-MgTeamPrimaryChannelMessageReplySoftDelete', 
               'Undo-MgTeamPrimaryChannelMessageSoftDelete', 
               'Undo-MgTeamworkDeletedChatDelete', 
               'Undo-MgTeamworkDeletedTeamChannelMessageReplySoftDelete', 
               'Undo-MgTeamworkDeletedTeamChannelMessageSoftDelete', 
               'Undo-MgUserChatMessageReplySoftDelete', 
               'Undo-MgUserChatMessageSoftDelete', 'Update-MgAppCatalogTeamApp', 
               'Update-MgAppCatalogTeamAppDefinition', 
               'Update-MgAppCatalogTeamAppDefinitionBot', 'Update-MgChat', 
               'Update-MgChatInstalledApp', 'Update-MgChatLastMessagePreview', 
               'Update-MgChatMember', 'Update-MgChatMessage', 
               'Update-MgChatMessageReply', 
               'Update-MgChatMessageReplyHostedContent', 
               'Update-MgChatPermissionGrant', 'Update-MgChatPinnedMessage', 
               'Update-MgChatTab', 'Update-MgGroupTeamChannel', 
               'Update-MgGroupTeamChannelMember', 
               'Update-MgGroupTeamChannelMessage', 
               'Update-MgGroupTeamChannelMessageHostedContent', 
               'Update-MgGroupTeamChannelMessageReply', 
               'Update-MgGroupTeamChannelMessageReplyHostedContent', 
               'Update-MgGroupTeamChannelSharedWithTeam', 
               'Update-MgGroupTeamChannelTab', 'Update-MgGroupTeamInstalledApp', 
               'Update-MgGroupTeamMember', 'Update-MgGroupTeamOperation', 
               'Update-MgGroupTeamPermissionGrant', 'Update-MgGroupTeamPhoto', 
               'Update-MgGroupTeamPrimaryChannel', 
               'Update-MgGroupTeamPrimaryChannelMember', 
               'Update-MgGroupTeamPrimaryChannelMessage', 
               'Update-MgGroupTeamPrimaryChannelMessageHostedContent', 
               'Update-MgGroupTeamPrimaryChannelMessageReply', 
               'Update-MgGroupTeamPrimaryChannelMessageReplyHostedContent', 
               'Update-MgGroupTeamPrimaryChannelSharedWithTeam', 
               'Update-MgGroupTeamPrimaryChannelTab', 
               'Update-MgGroupTeamScheduleDayNote', 
               'Update-MgGroupTeamScheduleOfferShiftRequest', 
               'Update-MgGroupTeamScheduleOpenShift', 
               'Update-MgGroupTeamScheduleOpenShiftChangeRequest', 
               'Update-MgGroupTeamScheduleSchedulingGroup', 
               'Update-MgGroupTeamScheduleShift', 
               'Update-MgGroupTeamScheduleSwapShiftChangeRequest', 
               'Update-MgGroupTeamScheduleTimeCard', 
               'Update-MgGroupTeamScheduleTimeOff', 
               'Update-MgGroupTeamScheduleTimeOffReason', 
               'Update-MgGroupTeamScheduleTimeOffRequest', 'Update-MgGroupTeamTag', 
               'Update-MgGroupTeamTagMember', 'Update-MgTeam', 
               'Update-MgTeamChannel', 'Update-MgTeamChannelMember', 
               'Update-MgTeamChannelMessage', 'Update-MgTeamChannelMessageReply', 
               'Update-MgTeamChannelMessageReplyHostedContent', 
               'Update-MgTeamChannelSharedWithTeam', 'Update-MgTeamChannelTab', 
               'Update-MgTeamInstalledApp', 'Update-MgTeamMember', 
               'Update-MgTeamOperation', 'Update-MgTeamPermissionGrant', 
               'Update-MgTeamPhoto', 'Update-MgTeamPrimaryChannel', 
               'Update-MgTeamPrimaryChannelMember', 
               'Update-MgTeamPrimaryChannelMessage', 
               'Update-MgTeamPrimaryChannelMessageReply', 
               'Update-MgTeamPrimaryChannelMessageReplyHostedContent', 
               'Update-MgTeamPrimaryChannelSharedWithTeam', 
               'Update-MgTeamPrimaryChannelTab', 'Update-MgTeamScheduleDayNote', 
               'Update-MgTeamScheduleOfferShiftRequest', 
               'Update-MgTeamScheduleOpenShift', 
               'Update-MgTeamScheduleOpenShiftChangeRequest', 
               'Update-MgTeamScheduleSchedulingGroup', 
               'Update-MgTeamScheduleShift', 
               'Update-MgTeamScheduleSwapShiftChangeRequest', 
               'Update-MgTeamScheduleTimeCard', 'Update-MgTeamScheduleTimeOff', 
               'Update-MgTeamScheduleTimeOffReason', 
               'Update-MgTeamScheduleTimeOffRequest', 'Update-MgTeamTag', 
               'Update-MgTeamTagMember', 'Update-MgTeamwork', 
               'Update-MgTeamworkDeletedChat', 'Update-MgTeamworkDeletedTeam', 
               'Update-MgTeamworkDeletedTeamChannel', 
               'Update-MgTeamworkDeletedTeamChannelMember', 
               'Update-MgTeamworkDeletedTeamChannelMessage', 
               'Update-MgTeamworkDeletedTeamChannelMessageHostedContent', 
               'Update-MgTeamworkDeletedTeamChannelMessageReply', 
               'Update-MgTeamworkDeletedTeamChannelMessageReplyHostedContent', 
               'Update-MgTeamworkDeletedTeamChannelSharedWithTeam', 
               'Update-MgTeamworkDeletedTeamChannelTab', 
               'Update-MgTeamworkTeamAppSetting', 
               'Update-MgTeamworkWorkforceIntegration', 'Update-MgUserChat', 
               'Update-MgUserChatInstalledApp', 
               'Update-MgUserChatLastMessagePreview', 'Update-MgUserChatMember', 
               'Update-MgUserChatMessage', 'Update-MgUserChatMessageHostedContent', 
               'Update-MgUserChatMessageReply', 
               'Update-MgUserChatMessageReplyHostedContent', 
               'Update-MgUserChatPermissionGrant', 
               'Update-MgUserChatPinnedMessage', 'Update-MgUserChatTab', 
               'Update-MgUserTeamwork', 'Update-MgUserTeamworkAssociatedTeam'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoOQYJKoZIhvcNAQcCoIIoKjCCKCYCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCNwF4SlUclqaPW
# E9S+Yt9RGoVKx3WTgN+zyoN9rkHze6CCDYUwggYDMIID66ADAgECAhMzAAAEA73V
# lV0POxitAAAAAAQDMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTEzWhcNMjUwOTExMjAxMTEzWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCfdGddwIOnbRYUyg03O3iz19XXZPmuhEmW/5uyEN+8mgxl+HJGeLGBR8YButGV
# LVK38RxcVcPYyFGQXcKcxgih4w4y4zJi3GvawLYHlsNExQwz+v0jgY/aejBS2EJY
# oUhLVE+UzRihV8ooxoftsmKLb2xb7BoFS6UAo3Zz4afnOdqI7FGoi7g4vx/0MIdi
# kwTn5N56TdIv3mwfkZCFmrsKpN0zR8HD8WYsvH3xKkG7u/xdqmhPPqMmnI2jOFw/
# /n2aL8W7i1Pasja8PnRXH/QaVH0M1nanL+LI9TsMb/enWfXOW65Gne5cqMN9Uofv
# ENtdwwEmJ3bZrcI9u4LZAkujAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU6m4qAkpz4641iK2irF8eWsSBcBkw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMjkyNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AFFo/6E4LX51IqFuoKvUsi80QytGI5ASQ9zsPpBa0z78hutiJd6w154JkcIx/f7r
# EBK4NhD4DIFNfRiVdI7EacEs7OAS6QHF7Nt+eFRNOTtgHb9PExRy4EI/jnMwzQJV
# NokTxu2WgHr/fBsWs6G9AcIgvHjWNN3qRSrhsgEdqHc0bRDUf8UILAdEZOMBvKLC
# rmf+kJPEvPldgK7hFO/L9kmcVe67BnKejDKO73Sa56AJOhM7CkeATrJFxO9GLXos
# oKvrwBvynxAg18W+pagTAkJefzneuWSmniTurPCUE2JnvW7DalvONDOtG01sIVAB
# +ahO2wcUPa2Zm9AiDVBWTMz9XUoKMcvngi2oqbsDLhbK+pYrRUgRpNt0y1sxZsXO
# raGRF8lM2cWvtEkV5UL+TQM1ppv5unDHkW8JS+QnfPbB8dZVRyRmMQ4aY/tx5x5+
# sX6semJ//FbiclSMxSI+zINu1jYerdUwuCi+P6p7SmQmClhDM+6Q+btE2FtpsU0W
# +r6RdYFf/P+nK6j2otl9Nvr3tWLu+WXmz8MGM+18ynJ+lYbSmFWcAj7SYziAfT0s
# IwlQRFkyC71tsIZUhBHtxPliGUu362lIO0Lpe0DOrg8lspnEWOkHnCT5JEnWCbzu
# iVt8RX1IV07uIveNZuOBWLVCzWJjEGa+HhaEtavjy6i7MIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAQDvdWVXQ87GK0AAAAA
# BAMwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIN/n
# xtyFG6SNIajyBQeEuPaf1U613RZg864KcW/Am949MEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAWjNjY1QoV3U4US77TyO/wr8Y+wzo1PdS7JSz
# Cbo+2dLbN7eUmUpW4xieA8qVyX1g70ryyFTezX8OWLTxlUGxgDox3uStfGeQAOGG
# xI9U3cbxmJOrgMSKJ9htO9b+U8CU8P2mXLLqKxPzoJpg0eFY4A0/TnCU1zNJFGz2
# +z98zVYkzn5UeR1WMZSpOriTPP6Hqq/wEZWx3CiN2xPHzLx0Msifla4CHoeBy/l5
# CxgiJVhr+Jkrc90zts7eMoMoErLO5p/XyG2/zUc8SOCgM05WQ//UVaJYiFQfAgcb
# K9ehzqltzcE5EE04fGSJMVBv40tyoNMihijlv0C6RYAKewkdWKGCF5QwgheQBgor
# BgEEAYI3AwMBMYIXgDCCF3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCAgy8z27UiUBNaHtai93zk92G6Pg/wjPkbY
# wPgSQ+d7sAIGaErgqM8bGBMyMDI1MDcxNjIyNDYyNy45NzRaMASAAgH0oIHRpIHO
# MIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQL
# ExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxk
# IFRTUyBFU046QTAwMC0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1l
# LVN0YW1wIFNlcnZpY2WgghHqMIIHIDCCBQigAwIBAgITMwAAAgh4nVhdksfZUgAB
# AAACCDANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDAeFw0yNTAxMzAxOTQyNTNaFw0yNjA0MjIxOTQyNTNaMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046QTAwMC0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Uw
# ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC1y3AI5lIz3Ip1nK5BMUUb
# GRsjSnCz/VGs33zvY0NeshsPgfld3/Z3/3dS8WKBLlDlosmXJOZlFSiNXUd6DTJx
# A9ik/ZbCdWJ78LKjbN3tFkX2c6RRpRMpA8sq/oBbRryP3c8Q/gxpJAKHHz8cuSn7
# ewfCLznNmxqliTk3Q5LHqz2PjeYKD/dbKMBT2TAAWAvum4z/HXIJ6tFdGoNV4WUR
# ZswCSt6ROwaqQ1oAYGvEndH+DXZq1+bHsgvcPNCdTSIpWobQiJS/UKLiR02KNCqB
# 4I9yajFTSlnMIEMz/Ni538oGI64phcvNpUe2+qaKWHZ8d4T1KghvRmSSF4YF5DNE
# JbxaCUwsy7nULmsFnTaOjVOoTFWWfWXvBuOKkBcQKWGKvrki976j4x+5ezAP36fq
# 3u6dHRJTLZAu4dEuOooU3+kMZr+RBYWjTHQCKV+yZ1ST0eGkbHXoA2lyyRDlNjBQ
# coeZIxWCZts/d3+nf1jiSLN6f6wdHaUz0ADwOTQ/aEo1IC85eFePvyIKaxFJkGU2
# Mqa6Xzq3qCq5tokIHtjhogsrEgfDKTeFXTtdhl1IPtLcCfMcWOGGAXosVUU7G948
# F6W96424f2VHD8L3FoyAI9+r4zyIQUmqiESzuQWeWpTTjFYwCmgXaGOuSDV8cNOV
# QB6IPzPneZhVTjwxbAZlaQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFKMx4vfOqcUT
# gYOVB9f18/mhegFNMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8G
# A1UdHwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y3JsL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBs
# BggrBgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUy
# MDIwMTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUH
# AwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQBRszKJKwAfswqd
# aQPFiaYB/ZNAYWDa040XTcQsCaCua5nsG1IslYaSpH7miTLr6eQEqXczZoqeOa/x
# vDnMGifGNda0CHbQwtpnIhsutrKO2jhjEaGwlJgOMql21r7Ik6XnBza0e3hBOu4U
# BkMl/LEX+AURt7i7+RTNsGN0cXPwPSbTFE+9z7WagGbY9pwUo/NxkGJseqGCQ/9K
# 2VMU74bw5e7+8IGUhM2xspJPqnSeHPhYmcB0WclOxcVIfj/ZuQvworPbTEEYDVCz
# SN37c0yChPMY7FJ+HGFBNJxwd5lKIr7GYfq8a0gOiC2ljGYlc4rt4cCed1XKg83f
# 0l9aUVimWBYXtfNebhpfr6Lc3jD8NgsrDhzt0WgnIdnTZCi7jxjsIBilH99pY5/h
# 6bQcLKK/E6KCP9E1YN78fLaOXkXMyO6xLrvQZ+uCSi1hdTufFC7oSB/CU5RbfIVH
# XG0j1o2n1tne4eCbNfKqUPTE31tNbWBR23Yiy0r3kQmHeYE1GLbL4pwknqaip1BR
# n6WIUMJtgncawEN33f8AYGZ4a3NnHopzGVV6neffGVag4Tduy+oy1YF+shChoXdM
# qfhPWFpHe3uJGT4GJEiNs4+28a/wHUuF+aRaR0cN5P7XlOwU1360iUCJtQdvKQaN
# AwGI29KOwS3QGriR9F2jOGPUAlpeEzCCB3EwggVZoAMCAQICEzMAAAAVxedrngKb
# SZkAAAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmlj
# YXRlIEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIy
# NVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
# B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UE
# AxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXI
# yjVX9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjo
# YH1qUoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1y
# aa8dq6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v
# 3byNpOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pG
# ve2krnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viS
# kR4dPf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYr
# bqgSUei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlM
# jgK8QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSL
# W6CmgyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AF
# emzFER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIu
# rQIDAQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIE
# FgQUKqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWn
# G1M1GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEW
# M2h0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5
# Lmh0bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBi
# AEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV
# 9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3Js
# Lm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAx
# MC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2
# LTIzLmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv
# 6lwUtj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZn
# OlNN3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1
# bSNU5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4
# rPf5KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU
# 6ZGyqVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDF
# NLB62FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/
# HltEAY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdU
# CbFpAUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKi
# excdFYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTm
# dHRbatGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZq
# ELQdVTNYs6FwZvKhggNNMIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJp
# Y2EgT3BlcmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkEwMDAtMDVF
# MC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMK
# AQEwBwYFKw4DAhoDFQCNkvu0NKcSjdYKyrhJZcsyXOUTNKCBgzCBgKR+MHwxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jv
# c29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7CIvCDAi
# GA8yMDI1MDcxNjE0MDA0MFoYDzIwMjUwNzE3MTQwMDQwWjB0MDoGCisGAQQBhFkK
# BAExLDAqMAoCBQDsIi8IAgEAMAcCAQACAgnNMAcCAQACAhJOMAoCBQDsI4CIAgEA
# MDYGCisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAI
# AgEAAgMBhqAwDQYJKoZIhvcNAQELBQADggEBAHpNHByWOeodb+st+LwnGbtiIJN9
# JqSPRk17vvF+XG6BgMQ7PEWuq2jYF/fdP78FLZjggkHyd5nn42ANEmjI2LeqZBU9
# 1h9Om+/BkLXBd/Ft63Mqa3PymkU2k17Qdl9Nge8REEcFkBcoSFs5Z7Odq2XSYO0u
# EqMrs/DpMq+1UfT/SrFfZt+CuVK+WFyI8Af6lsKOZDXNQOa83xpjYr5Kt9kxeACo
# TR0Y8QQ10xxB2913vN1qgQekoJvEsu85Vx7mwBAt2x+VjEmCbgUT7SEMEy027s0k
# 3E1eqc7CNt0OEBLDJWeE9WhGYS6hekdzOewhwcRufcIDReuNkJPxKWy7yC4xggQN
# MIIECQIBATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQ
# MA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
# MSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAgh4
# nVhdksfZUgABAAACCDANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0G
# CyqGSIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCBadU7BIiwySdTVZj7ByscPJ1bJ
# EY2nAePvcN9cdqejKjCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EII//jm8J
# Ha2W1O9778t9+Ft2Z5NmKqttPk6Q+9RRpmepMIGYMIGApH4wfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAIIeJ1YXZLH2VIAAQAAAggwIgQgSTDVRz1I
# cwDQaQgWeHduipe3q6uLPZ1p11fa5oH5algwDQYJKoZIhvcNAQELBQAEggIAoP7y
# 72tytUoZIWqeWKrR/rXxcS407B3hCeavDfOAVMPqs4sFN+Fzzlinxe47u+9xMTzp
# gBhv667TmZftHxs+wvn12+kNlqz5Au3y29c9MP3OiX+6qAeQdCjkVYDdastwGpDZ
# Np/4JS7pA8so6L3HCiaJ+6vxrer3b9PDG4kTaxkEV3jBb9YnNaSLphxRwaLk4a6l
# aY2qZbukTWvMeWpEBfWNQyNhmTTJnKxh9QaUjVzupq03iidc4tuk1AwrvoPBXGF1
# SPH6mP0EjUEeHG54tmSdtNt6SAdKkY7UWIGNfwOZxXYLgVUSHb5UpIwhxDllPPl3
# fPLyuDUv4oU/pM438wjfP1y30RIsL8VmfqQGFnaN6qp/BBhzEShmbfRVC6qNrwxx
# mwJA2lG7Jpk7NAYyixYzaFXLGaTNV9QnAlWpnhcll8b1Tu3hbKGEgtVHwv+sD/HH
# EIphKiQmvflvsVVIewWsUqHw7Xars7orgebuDqBHActRq2Hk2JR+7hO2JZYuAwR4
# kRbeCBTcaWdMqYUFlNFMG0EWZyg0chERzAbCLlh05gUAuwD9jnGT5qMQ1zxwIaiW
# jlm4d97qpspF7m/Upfn8BLBs8/3C3N7HylKWG0HFXt4qZbPixj/QuyPzx6hWSyf7
# ELzHxPGN2R8xrb58FrpZvZO7oOg3rCZUz7KpJFs=
# SIG # End signature block
